import { Poppins, Nunito } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const nunito = Nunito({
  weight: ['400', '600', '700'],
  subsets: ["latin"],
  variable: "--font-nunito",
});


export const metadata = {
  title: "Adoração Deviocional",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${nunito.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
